### PR TITLE
Fix issue undefined method 'transform'

### PR DESCRIPTION
**Pull request by reivaxm**
Simple patch like joallard say to fix with jekyll 3.3.0 and later
https://github.com/samvincent/jekyll-haml/issues/19

Rel to #19

### CODE REVIEW

**Comment by joallard** [comment]
But does it make it work?

**Comment by tomquinonero** [comment]
It seems to work.
I got the problem with the version 3.3.1 of jekyll and using following line in my Gemfile resolved it.

> gem 'jekyll-haml', :git => 'https://github.com/reivaxm/jekyll-haml.git', :branch => 'fix/jekyll-3.3.0_issue'

**Comment by reivaxm** [comment]
Yes, it has been tested with jekyll 3.3.0 and 3.3.1 and haml file are correctly generated.

**Comment by joallard** [comment]
Any chance I can get the commit credit on that source diff? ;)

**Comment by jlxw** [comment]
@samvincent accept? :)

**Comment by reivaxm** [comment]
Yes of courses !

**Comment by samvincent** [comment]
`jekyll-haml (0.1.5)` released. Thanks guys.

**Pull request merged**
