### PR TITLE
Fixed an error with Jekyll 2.3.0 (and probably with prior versions) that crashes when building the site

### PR DESCRIPTION
**Pull request by kalvinarts**
I was getting this error:

```
jekyll 2.3.0 | Error:  undefined local variable or method `path' for #<Jekyll::Layout:0x007fda29134420>
```
Fixed by correctly redeclaring the Layout class inheriting by the original one.

@yaegashi and @felixkiss solutions are integrated as well.

### CODE REVIEW

**Comment by reivaxm** [comment]
It fix also the bug with the last version of jekyll
jekyll 3.0.0.pre.beta8 | Error:  no implicit conversion of nil into String

**Comment by JangoSteve** [comment]
:+1: fixes same error for me as @reivaxm pointed out for jekyll 3.0.1.

```
jekyll 3.0.1 | Error:  no implicit conversion of nil into String
```

**Comment by deathbeam** [comment]
Same error happening in latest jekyll to me too.

**Comment by samvincent** [comment]
Thanks @kalvinarts, Merged and released as 0.1.3

**Pull request merged**
